name: commit

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  job1:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA

  job2:
    needs:
      - job1
    uses: ./.github/workflows/workflow_call.yml
    with:
      sample: ${{ contains(github.event.pull_request.labels.*.name, 'sample-label') && 'sample-label' || 'nothing' }}
