name: commit

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  job1:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA

