name: environment

on:
  push:

jobs:
  deployment1:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hello'
  deployment2:
    needs: [deployment1]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo 'hellooooo'
